name: edumate
description: A multi-language college chatbot with voice support

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^0.13.6
  
  # Text-to-Speech
  flutter_tts: ^3.8.5
  
  # Speech-to-Text  
  speech_to_text: ^6.3.0
  
  # Translation
  translator: '>=0.1.6 <1.0.4+1'
  
  # Language detection
  google_mlkit_language_id: ^0.9.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # Shared preferences
  shared_preferences: ^2.2.2
  
  # Path provider
  path_provider: ^2.1.1
  
  # Audio player (for voice messages)
  audioplayers: ^5.2.1
  
  # UUID generation
  uuid: ^4.1.0
  
  # Animations
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  
  # UI components
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    
  # Uncomment and add font files when available
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700